### ISSUE TITLE
7th Tradition, Recuring Expenses, Prudent Reserve

### ISSUE THREAD

**Issue by wleibrook** [recoverysource/recoverysource.github.io#2]
There are 2 statemnt that seem to contradict- Can you calrify?

We do not accept donations from the groups we serve and encourage new group members to contribute time and effort, rather than financial resources.

This table lists maximum contributions that can currently be accepted:
Cost | Item
-- | --
$75* | 5 yr Registration for https://recoverysource.net/
$40 | 2 yr Registration for https://sobersupport.group/
$274* | 8 yr Registration for https://sober.page/

I don't exactly understand aall of this.

**Comment by MTecknology** [comment]
AA's 7th Tradition States:
> The A.A. groups themselves ought to be fully supported by the voluntary contributions of their own members. We think that each group should soon achieve this ideal; that any public solicitation of funds using the name of Alcoholics Anonymous is highly dangerous, whether by groups, clubs, hospitals, or other outside agencies; that acceptance of large gifts from any source, or of contributions carrying any obligation whatever, is unwise. Then, too, we view with much concern those A.A. treasuries which continue, beyond prudent reserves, to accumulate funds for no stated A.A. purpose. Experience has often warned us that nothing can so surely destroy our spiritual heritage as futile disputes over property, money, and authority.

In general, this tradition is intended to maintain the (spiritual) integrity of the group and to prevent disputes over property/money and it lays out some practical guidelines to apply these principles. Some of my favorite meetings encourage newcomers to "save the dollar" until they feel like they're part of the group.

Recovery Source is particularly likely to encounter groups that are struggling with technology, which likely includes excessive costs; helping groups to resolve these financial woes is likely to leave them feeling obligated to share some of the recovered funds with us. This creates a number of potential issues that are best avoided entirely.

In the same way that newcomers are encouraged to focus on their sobriety first and foremost, we too wish for the groups we serve to focus on their outreach. ("save the dollar [and focus on recovery]")

This same spirit extends to our project members. There /is/ financial overhead, and that's something for project members to help with, but we would much rather that new members contribute time and effort.

**Comment by MTecknology** [comment]
This might be a better summary ...
> Groups should focus on outreach.
> New project members should focus on groups.
> Old project members should focus on new project members, and groups
